### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by hamzeyto** [mahtorohit/Android-Call-Sms-Blocker#1]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by mahtorohit** [comment]
I prefer to keep it MIT licensed, If you can add that then it will great. Please go ahead & add MIT license if you can & raise a pull request for the same.

**Comment by mahtorohit** [comment]
Hey Hamzeto,
Thanks for pointing it out. I found the existing template which was super easy to add Licence. If can improve the Readme then please go ahead & add merge request will happy to merge it
