### ISSUE TITLE
Issues of logo/icon

### ISSUE THREAD

**Issue by hafizahmmed** [mahtorohit/Android-Call-Sms-Blocker#3]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![android-call-sms-blocker-01](https://user-images.githubusercontent.com/38810169/39536562-c90bd72c-4e58-11e8-9659-f1e87290cd86.jpg)

thank you.

**Comment by mahtorohit** [comment]
Thanks @hafizahmmed, am still working on this project it might take few weeks to improve this in UI wise. Will happy to use your icon. You can give a merge request by updating the icon. Will be happy to merge it. Or you can post the icon SVG/PSD in a comment.

**Comment by hafizahmmed** [comment]
[Android-Call-Sms-Blocker.pdf](https://github.com/mahtorohit/Android-Call-Sms-Blocker/files/1970432/Android-Call-Sms-Blocker.pdf)

**Comment by hafizahmmed** [comment]
https://drive.google.com/open?id=1g8sPYLMBimAyWsSXIIljMwgo22zZmOM2

**Comment by mahtorohit** [comment]
@hafizahmmed thanks for your contribution.
