### ISSUE TITLE
Logo for Android-Call-Sms-Blocker

### ISSUE THREAD

**Issue by familqasimov** [mahtorohit/Android-Call-Sms-Blocker#4]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![1](https://user-images.githubusercontent.com/36432269/39545016-e53ca770-4e60-11e8-9e41-b0a8aab9afd4.png)

**Comment by mahtorohit** [comment]
Thanks @familqasimov, am still working on this project it might take few weeks to improve this in UI wise. Will happy to take your help to improve the UI / screens. You can post the layout over here / raise a merge request for the same.

**Comment by familqasimov** [comment]
I have a few works in Hospital. I can send you PR in yesterday, if you want.

Best regards
Famil Qasimov

3 may 2018, C.A. 12:27 tarixində Rohit Mahto <notifications@github.com>
yazdı:
